### ISSUE TITLE
Problem on pickle protcol

### ISSUE THREAD

**Issue by kzhk75** [gpoore/pythontex#116]
Hi,

I met the followoing error with MacTex2017 + brewed Python{2,3}:
> $ pythontex test.pytxcode 
>  This is PythonTeX 0.16
> Traceback (most recent call last):
>   File "/Library/TeX/texbin/pythontex", line 62, in <module>
>     pythontex.main()
>   File "/usr/local/texlive/2017/texmf-dist/scripts/pythontex/pythontex2.py", line 2701, in main
>     get_old_data(data, old_data, temp_data)
>   File "/usr/local/texlive/2017/texmf-dist/scripts/pythontex/pythontex2.py", line 592, in get_old_data
>     old = pickle.load(f)
> ValueError: unsupported pickle protocol: 4

But  it works below:
> python3 $(which pythontex) test.pytxcode
> This is PythonTeX 0.16
> 
> --------------------------------------------------
> PythonTeX:  ExamPhysI24Oct2017 - 0 error(s), 0 warning(s)

Could I fix this error?

**Comment by gpoore** [comment]
That could be due to compiling a document with Python 3.4+, and then trying to use it with an earlier version of Python. You can delete the `.pkl` file in the `pythontex-files` directory, and then everything should work fine. That file is just a cache, so deleting it will just mean that all code is executed on the next compile.

**Comment by kzhk75** [comment]
After remove *.pkl" file in the "pythontex-files directory, I can compile *.pytxcode.
Thanks
