### ISSUE TITLE
Aligning Matplotlib fonts with the rest of the document

### ISSUE THREAD

**Issue by seishonagon** [gpoore/pythontex#117]
When using matplotlib (e.g. the example in the pythontex gallery) the font always seems to default to CM fonts, even if though my own math fonts is set to XITS. I've tried using the rc parameters, for example: 
`rc('text', usetex=True)`
`rc('font', family='serif')`
`rc('font', serif=['xits-math.otf'])`
`rc('font', size=10.0)`
`rc('legend', fontsize=10.0)`
`rc('font', weight='normal')`

but whatever combination of parameters I use, I still get the same old CM fonts. Is there an example of font switching that I could look at, because I'm obviously doing something wrong.

**Comment by gpoore** [comment]
If you're trying to work with an `.otf` font, I think you'll want to use the XeTeX or LuaTeX engine, and probably also need to specify the font name differently. That will all be related to matplotlib instead of anything PythonTeX is doing. Take a look at https://matplotlib.org/users/pgf.html for some examples.
