### ISSUE TITLE
Setting path to python.exe explicitly

### ISSUE THREAD

**Issue by thatlittleboy** [gpoore/pythontex#123]
I have Python 3.6.3 installed via Anaconda on Windows 10, 64 bit. For reasons that I will not go into, `python.exe` etc. are not in my PATH, and so if I want to run python in the command line, I will use the Anaconda prompt instead of using the default Windows command prompt (apparently, this is also the recommended way, according to Anaconda devs). 

For what I believe to be the same reason,  I am having issues calling `pythontex`:

In the command prompt in Windows, calling `pythontex` gives the error message:
```
pythontex: The script engine could not be found.
pythontex: Data: scriptEngine="python.exe"
```

On the other hand, calling `pythontex` in Anaconda prompt:

![cmd_2018-03-04_16-12-36](https://user-images.githubusercontent.com/30731072/36947640-dee97b82-1fc6-11e8-8e65-d4f89e640d30.png)

and so `pythontex` can be found.

So is there anyway to pass the path of `python.exe` to pythontex as an optional argument?

Side note: my end goal is to be able to call `pythontex` in TeXstudio via its Build options. But I think I can figure that out. Right now, the same error ("script engine could not be found") is showing up in TeXstudio when I try to run pythontex.

**Comment by gpoore** [comment]
Your TeX distribution has a launcher for `pythontex.py`, and that launcher is giving the error message because it can't find `python.exe`. `pythontex` itself never even gets started. The launcher only works with things on PATH. If you don't want to have `python.exe` on your PATH, then you may want to create something like a batch file that is somewhere on your PATH, and it will need to use the full path to `python.exe` as well as the full path to `pythontex.py` within your TeX distribution. Or you could just do the same thing as a TeXstudio build rule, specifying the full paths to `python.exe` and `pythontex.py`. So instead of a build rule `pythontex <args>` you would have `<python_path>/python.exe <tex_path>/pythontex.py <args>`.

**Comment by thatlittleboy** [comment]
Ok, I will call explicitly: `<python_path>/python.exe <tex_path>/pythontex.py <args>`. This works for me at the moment, thanks!
