### ISSUE TITLE
Stability guarantee for generated files

### ISSUE THREAD

**Issue by muelli** [gpoore/pythontex#125]
It would help certain latex wrappers, e.g. latexmk, if there was some guarantee of stability for the names of the generated files.

Right now it seems that `.pytxcode`  and `pythontex-files-%R`, where %R is the base name of the main .tex document file, are important.

Can you commit on the stability of these filenames for a certain version of PythonTeX?  Then it may be possible to integrate PythonTeX into latexmk more closely.

**Comment by gpoore** [comment]
The `.pytxcode` has been used essentially since the beginning, and is guaranteed through at least version 0.18 (next release plus one, whenever I get to it). The same thing applies to the `pythontex-files-%R`, except that there is the additional complication that this can be customized by the user (though I doubt that many people are doing that).

I'm not sure about stability beyond v0.18, because I'm not sure about the future direction of the package. If I can find enough time for significant development again, I will probably work toward a new package that supersedes PythonTeX, providing a PythonTeX compability mode while fixing a lot of current limitations and providing better support for other languages. In that case, PythonTeX itself would see a few more updates, but the `.pytxcode` and `pythontex-files-%R` shouldn't ever change. The main scenario in which they might change is if I can only find time for less major improvements to PythonTeX itself. In that case, I'd be happy to submit an update request to latexmk or other projects if I planned a change, and there wouldn't be any changes without at least several months advance warning.
