### ISSUE TITLE
No console support for Sage ?

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [gpoore/pythontex#127]
Well, with 
```
\usepackage[usefamily={py,sage},gobble=auto]{pythontex}
```
in my preamble, this works : 
```
  \begin{sageblock}
    var("a,b,x")
    E=a*x+b
    S=E.solve(x)
  \end{sageblock}
```
As well as this : 
```
  \begin{pyconsole}
    a=1
    b=2
    a+b
  \end{pyconsole}
```
But this fails : 
```
  \begin{sageconsole}
    a=1
    b=2
    a+b
  \end{sageconsole}
```
with the following "explanation" (`*TeX Help*` buffer in AUCTeX...) : 
```
ERROR: LaTeX Error: Environment sageconsole undefined.

--- TeX said ---

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.3   \begin{sageconsole}
                         
--- HELP ---
LaTeX has encountered a \begin command for a nonexistent environment.
You probably misspelled the environment name. 
```
Ditto if I try `sagecon`.  Is this expected (i. e. partial implementation) or not (i. e. a bug) ?

I haven't been able to find a relevant issue (opened or closed) except [#63](https://github.com/gpoore/pythontex/issues/63) (closed about two years ago).

**Comment by EmmanuelCharpentier** [comment]
> There is no console support for Sage.

Ouch ! 

> Python console support is based on the code module in the Python standard library.

I'll have a look at this library in order to understand what it does and if some similar facilities exist in Sage (it might be the case : Sage is a not-inconsiderable layer of math code over a firm Pythn fondation).

> Thanks for your work with patchSynctex!

Let's be absolutely clear : as mentioned in the package documentation as well on the [relevant Github page](https://github.com/EmmanuelCharpentier/patchSynctex), [**Jan Gleixner**](https://github.com/jan-glx/patchKnitrSynctex) is the original author ; I just (mostly) wrapped his original implementation in a CRAN package and maintained it.

> R Markdown-style support for executing code in Pandoc Markdown

This is fast becoming a necessity : `rmarkdown` and `pandoc`, having a "gentler" learning curve than \LaTeX, are gaining users much faster than the latter. Given the popularity of Python, the availability of a "literate programming" tool using `pandoc` would be a boon.

A further advantage would be to avoid the use of `rmarkdown`, which entails the installation and *maintainance* of `R` and a non-negligible library in a language which is of marginal use to most Python users...

Furthermore, publication is less and less paper-oriented (i. e. PDF-oriented) nowadays.  The ability to produce good screen-oriented material (e. g. HTML5)  is more and more important. And the current \LaTeX-->HTML conversion tools are not yet up to par : even `pandoc` gib=ves you a *lot* of stumbling blocks...

> patchSynctex has given me some ideas about how to manage the LaTeX-PDF part.

I'm not sure the markdown-->\LaTeX-->[some output format] route is optimal ; Im not sure of the contrary either : 

I did some trials using \LaTeX fragments in a Markdown source (via `pandoc`) : so far, I'm not very happy with the results. The necessity of using some (again non-negligible) \TeX installation and library is not a great point either. A great thing might be to be able to use a \LaTeX-free solution (using mathml and/or mathjax for math typesetting).

On the other hand, not using \LaTeX also means kissing goodbye to the tons of good and tested code written for \LaTeX in the last 4 decennies...

BTW : your project would also enhance the interest of supporting `R` as one of the "available families" usable in PythonTeX...

**Comment by EmmanuelCharpentier** [comment]
Re: Use of Pythontex for Markdown files

FWIW, the enclosed `Sage1.md` file is correctly converted by `pandoc` to `Sage1.tex`, which `pdflatex` and `pythontex` correctly converts to `Sage1.pdf` ; `pandoc` itself cannot create `Sage1.pdf`, nor convert to `Sage1.epub`.

The resultant `.tex` file can also be (semi-)successfully "depythonyzed" as `Sage1DP.tex`, which allows for the creation of `Sage1DP.docx` and `Sage1DP.epub` versions. However, in these versions, I do not get the picture nor its caption (created via \LaTeX's `figure` environment...), but only the replacement text. Of note, `Sage1DP.pdf` correctly contains the picture and its caption.

One notes that the syntax I had to use to obtain this result is somewhat trichodynamic... and exceedingly `pandoc`-specific. This might let one think that a **pre**processing approach ("à la `knitr`") might come in handy...

HTH,

[Sage1.zip](https://github.com/gpoore/pythontex/files/2196019/Sage1.zip)

**Comment by gpoore** [comment]
> Let's be absolutely clear : as mentioned in the package documentation as well on the relevant Github page, Jan Gleixner is the original author ; I just (mostly) wrapped his original implementation in a CRAN package and maintained it.

I did see that note...but I also know that just packaging and maintaining can take some effort.

I don't see markdown-->LaTeX-->[other format] as a general approach. I just know that if I am writing markdown targeting HTML, at least part of the time I will also want the ability to generate PDF, and LaTeX will be the best way sometimes. (If PDF is the only output needed, it will often be best just to start with LaTeX.) I think I've solved line number synchronization between pandoc markdown-->HTML, so I thought I might as well try to do synctex for markdown-->LaTeX-->PDF. I just finished the markdown-->LaTeX part today.

In terms of **pre**processing: I'm trying to create a core program that manages code execution, along with multiple wrappers/interfaces for extracting code from a document and passing it to the core for execution. The first wrapper will use Pandoc to extract code, pass the code to the core for execution, and then use Pandoc to put the output back in the document. There will eventually be another wrapper that uses LaTeX to extract code--this will be more or less equivalent to PythonTeX. It will also be possible to create wrappers that extract code themselves via regex etc., rather than using an external program for parsing. That amounts to the preprocessing approach. Preprocessing has some advantages (especially simplicity) and is worth supporting. However, I often don't like it, because typically comments aren't recognized, so there can be weird escaping issues. Plus, if the syntax isn't designed carefully, it can require special editor support like syntax highlighting for even the non-code part of the document to function normally.
