### ISSUE TITLE
depythontex for Julia

### ISSUE THREAD

**Issue by mykelk** [gpoore/pythontex#145]
We're trying to use depythontex so that we can post to arxiv, but we're running into trouble in our use of Julia. We use:
```
\usepackage[usefamily={jl,julia}, depythontex]{pythontex}
```
We then get `main.depytx` after compiling.

We then run `depythontex` and get the following error: 
```
$ depythontex main.tex
* DePythonTeX error:
    Could not find command "juliav" on line 303
```
Looking at the documentation, it sounds as if Julia isn't supported yet by depythontex. Is there an easy way for us to add this functionality?

**Comment by gpoore** [comment]
depythontex should work automatically for arbitrary languages. I just checked, and it is working fine for simple Julia cases. My guess is that the document you're working with contains LaTeX that the depythontex parser currently can't handle. Can you look in your document to find the `\juliav` commands, especially any at or after line 303? My guess is that you have one in a caption or other location that the depythontex parser is having trouble resolving. Once I know what's causing the issue, there may be a way to fix this through patching depythontex or possibly modifying the LaTeX in your document.

**Comment by mykelk** [comment]
Yes, you're right. I do have a `\juliav` in an algorithm caption around that line.

**Comment by gpoore** [comment]
depythontex currently doesn't work when commands are inside other commands that read their arguments but don't typeset them until later. depythontex is looking for a particular command on a particular line (to avoid false positives), and the line numbering is thrown off by these sorts of commands. This includes captions.

If you only have a couple of these, the simplest thing to do would be to replace them manually with `\texttt`, or whatever `listings` or `minted` or other commands you are using for inline code in the final translated document.

Otherwise, I suppose it might be possible try something like a +/- 10 line search window to try to account for cases like that...although I don't think even that will work in the general case, because while that could account for the caption being typeset in the document body, it still won't work if the caption appears in a list of figures or equivalent.

**Comment by mykelk** [comment]
Got it. We'll do that. Thanks!
