### ISSUE TITLE
v016  (pylab, numpy, matplotlib) not working with texlive 2018 and anaconda 2019.03 (Python3.7)

### ISSUE THREAD

**Issue by schornhe** [gpoore/pythontex#146]
Dear all , 
I'm try to use pythontex v0.16 (from texlive2018 distro) together with the latest anaconda 2019.03

The example 
`\documentclass[parskip=half,fontsize=11,paper=a4]{scrartcl}
\usepackage{pythontex}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{graphicx}    % Einbinden von Graphiken
\usepackage[english, ngerman]{babel}

\begin{document}
	
\begin{pycode}	
from sympy import *
from numpy import *
x,y=symbols('x y')

y=2*sqrt(x*x+2*x+1)
dy=diff(y,x)
dy2=dy.evalf(subs={x:2})

\end{pycode}

Dies ist ein Test
Die Gleichung lautet \pyc{print(y)}
Die Ableitung lautet \pyc{print(dy)}  mit einen Wert bei 2 : \pyc{print(dy2)}
\end{document}`

the first call latex document.tex is working fine
the pythontex document.pytxcode gets an error message
`This is PythonTeX 0.16

----  Messages for py:default:default  ----
  Traceback (most recent call last):
* PythonTeX stderr - error on line 14:
    File "<outputdir>\py_default_default.py", line 53, in <module>
      from numpy import *
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
      from . import _distributor_init
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
      from . import _mklinit
  ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

--------------------------------------------------
PythonTeX:  document - 1 error(s), 0 warning(s)`

the same eerror occurs when using 

from pylab import *
from matplotlib import *

running the python code in e.g. sypder , no errors occur

**Comment by gpoore** [comment]
You're getting a DLL error, so there is some sort of issue with your Python installation. If there isn't an issue with spyder, then presumably it is running Python in a different manner that avoids the issues. You might take a look at https://stackoverflow.com/questions/54974444, or do a search to find more relevant debugging info for your case. I'd suggesting trying to solve this by running Python from the command line, instead of having PythonTeX involved, since that will be more direct. 

As far as your document goes, it works fine on my system, after I removed the unused numpy import and swapped `y=2*sqrt(x*x+2*x+1)`. You might consider something like `$\py{latex(y)}$` to access the calculated results.

**Comment by slel** [comment]
Typo in issue title: ,atplotlib -> matplotlib, please fix if possible.
