### ISSUE TITLE
Input template and pysub

### ISSUE THREAD

**Issue by pepramon** [gpoore/pythontex#159]
Hi.

I have a list of parameters to generate a document, I have text and a picture generated by tickz.

To do it, I prepare a file with latex code to generate it in a different file (using as a template) and use the environment pysub to define de points. I put all inside a for loop.

A simplified python code is
```python
for x in users:
        global longb       <<--- I use to have access inside the pysub
        longb=calculus(b)
        print(r'\input{template/userdraw}')
	print(r'\pagebreak')
```
and simplified LaTeX code inside userdraw.tex
```latex
  \begin{pysub}
  \begin{tikzpicture}
    \scaling{1};
    % Nodes 
    \point{a}{0}{1};
    \point{b}{!{longb}}{1};         <<---- The substitution
    \point{c}{9}{1};
  ........
  \end{pysub}
```

The problem is that the substitution on all pages generated are for the last case. Seems like  generate all latex code and do de prints at the end, with last info. I try to use different ways and search how can I do and didn't found anythink.

How can I flush the prints??? It's the correct way to do it??

Regards

---

Edit --> Atached example without pysub (using \py) it's the same problem. Main document carta.tex
[carta.zip](https://github.com/gpoore/pythontex/files/3722212/carta.zip)

**Comment by gpoore** [comment]
In the attached example, you have this:
```latex
\begin{pycode}
	
def generate(var):
	global id
	global name
	
	id=var[0]
	name=var[1]
	
	print(r'\input{letter}')
	return 0
\end{pycode}

\begin{pycode}
users=[[123456789,"Foo"],[987654321,"Bar"]]
for x in users:
	generate(x)
	print(r"\pagebreak")
\end{pycode}
```
In the loop at the end, you are setting variables (via `generate()`), printing `\input` (via `generate()`),  and printing `\pagebreak`. The issue is that the `\input`s are not processed until all of them are printed, at which point the variables have their final value from the loop. As long as the code within a `pycode` environment is running, LaTeX isn't doing anything and is waiting for the complete output (it's a little more complicated than that, but that's the basic effect). LaTeX only processes printed content after the end of an environment, not one line at a time during Python execution.

To get something like this to work the way you want, there are a few options. You could put the loop into LaTeX (maybe using tikz), and within a LaTeX loop call a Python function using `\py` that does what you want with each user and id.

Another option would be to have Python read `letter.tex` into a string, do all of the substitutions within Python, and then print the result (which would send it back to LaTeX). That's probably what I would do myself.

**Comment by pepramon** [comment]
Hi, I use the second option and works fine.

If somebody have de same problem I attach a simplified code than I use with dict to automate a little bit (I'm not a really good programmer, sorry):

Python code
```python
import csv

#Variables to use inside file
var ={
	"DNI": "123456",
	"nombre": "Some body",
}

#Read template and store inside var
template_file=open('latex/letter.tex', 'r')
template=template_file.read()
template_file.close()

#Read users CSV file
fusers=open('usuarios.csv','r')
users=csv.reader(fusers, delimiter=";")

for x in users:
        # Assign vars
	var["DNI"]=str(x[0])
	var["nombre"]=str(x[1])

        #Working template to save original
        work=template

        #Substitution and print result
        for data in var:
		s=r"\pinol"+data    <-- I use a prefix to avoid variable collisions
		work=work.replace(s,str(var[dato]))

        #Printing the result		
	print(work.decode('utf_8')) <-- I'm catalan and use ÇÑà...
        print(r'\pagebreak')
```

And LaTeX document (really simple
```latex
Your name is \pinolnombre and your id card is \pinolDNI
```

Whit this configuration, the LaTeX document is a normal document (and can use without Pythontex) if you define variables.

Geoffrey Poore really thanks
