### ISSUE TITLE
depythontex: \py is not working with align 

### ISSUE THREAD

**Issue by samjohn24** [gpoore/pythontex#160]
Hi,

I'm trying to use \py inside an align environment on the following way:
```
\begin{align}
       D_\infty() &= \py{a1} + \py{a2} + \py{a3} \nonumber \\
                   &= \py{a4}
      \label{eq:D_inf}
\end{align}
```
But depythontex throw me:

`* DePythonTeX error:
    Could not find command "py" on line 1129
`
I tried the same in equation environment with no problem.

**Comment by gpoore** [comment]
`align` does some special processing to do the alignment, and this can interfere with `depythontex`. If I remember correctly, `align` captures the entire environment contents and then processes it multiple times, which throws off line numbering since commands are actually processed later than they appear. Probably the easiest alternative is to use `pysub` instead.

```latex
\begin{pysub}
\begin{align}
       D_\infty() &= !{a1} + !{a2} + !{a3} \nonumber \\
                   &= !{a4}
      \label{eq:D_inf}
\end{align}
\end{pysub}
```

**Comment by samjohn24** [comment]
Thanks for the support @gpoore, works fine with `pysub`. I was trying alternative methods and turns out that, for this specific case, also works with aligned (don't know why):

```
\begin{equation}
        \begin{aligned}
       D_\infty() &= \py{a1} + \py{a2} + \py{a3} \\
                   &= \py{a4}
        \end{aligned}
        \label{eq:D_inf}
\end{equation}
```
