### ISSUE TITLE
PythonTex error on Mac

### ISSUE THREAD

**Issue by IgorDouven** [gpoore/pythontex#169]
I have TeX Live 2019 installed on a Mac. When I call `pythontex` (or `pythontex.py`, or `pythontex3`, ...) on a tex file after first having called `pdflatex` (or `lualatex`, or `xelatex`, or ...) I get the following error:
```
This is PythonTeX 0.17
* PythonTeX error
    The version of the PythonTeX scripts does not match the last code
    saved by the document--run LaTeX to create an updated version.
```
I can't figure out what's wrong. Any suggestions would be appreciated.

**Comment by gpoore** [comment]
This looks like you may have multiple versions of `pythontex` installed, or possibly multiple copies of `pythontex.sty`, and they are in conflict due to different versions. What do you get from running `which pythontex` and `pythontex --version` on the command line? Can you track down `pythontex.sty` in TeX Live or elsewhere to see if there are multiple copies around?

**Comment by IgorDouven** [comment]
Thanks for your prompt reply. It's certainly possible that I have multiple
versions of `pythontex` installed. Nevertheless, `pythontex --version`
yields PythonTex 0.17, and `which pythontex` yields
`/Library/TeX/texbin/pythontex`. If I look there, I find that `pythontex`
is symlinked, and running `realpath ./pythontex` yields
`/usr/local/texlive/2019/texmf-dist/scripts/pythontex/pythontex.py`. If I
look in the directory of that file and run `cat README`, that also appears
to be version 0.17.

Op za 25 jul. 2020 om 15:07 schreef Geoffrey Poore <notifications@github.com

**Comment by gpoore** [comment]
The other thing to check would be `pythontex.sty` in `/usr/local/texlive/2019/texmf-dist/scripts/pythontex/`. It should have `\newcommand{\pytx@packageversion}{0.17}` around line 26. You might also do a file search to see if there are any other copies of `pythontex.sty` around.

When you run `pdflatex`, the `pythontex` package saves all of the code in the document to a temp file. `pythontex.py` then executes the code. The issue is that the versions don't match up between `pythontex.sty` and `pythontex.py`.

**Comment by IgorDouven** [comment]
Thanks, this is very helpful. I checked the style file and that's OK
(version 0.17). I looked for other copies of `pythontex.sty` and the only
ones are in previous TeXLive distributions. But checking the .pytxcode file
was very informative: it says that v0.18dev was called. I did, a couple of
days ago, git clone the repo, but then I downloaded the package from CTAN
and went with that. I removed the repo and can't find the development
version anywhere on my computer. How come pdflatex is still calling it?

Op za 25 jul. 2020 om 17:54 schreef Geoffrey Poore <notifications@github.com

**Comment by gpoore** [comment]
Having v0.18dev installed previously probably does explain this somehow. If the dev version is indeed completely uninstalled, perhaps there's still a copy in a cache somewhere.

Have you tried deleting the `pythontex-files-*` directory in the document directory? I don't expect that will do anything, but it might be worth trying.

**Comment by IgorDouven** [comment]
I don't have that directory. The log of pdflatex says that there is not
pythontex-files-[document name]/[document-name].pytxmcr and then says that
I should run PythonTeX to create it. But that errors then.

Might it make sense to clone the GitHub repo again and then replace the
pythontex directory in the TeXLive distribution by that one? Wouldn't I
then be calling v0.18dev on a document that expects that version?

Op za 25 jul. 2020 om 19:08 schreef Geoffrey Poore <notifications@github.com

**Comment by gpoore** [comment]
Switching to v0.18dev could work for now. The only issue with that is that whenever v0.18 is released, the problems may start again.

**Comment by IgorDouven** [comment]
Thanks, this solved the immediate issue. But I needed pythontex to typeset
Julia code, and for that I also need a package developed by Mykel
Kochenderfer -- which unfortunately requires v0.17. I'll wait for now. I
can do the typesetting on my Linux machine, where everything runs fine. It
would have been nice to get this working on my Mac as well, but no real
problem. Thanks again for your help.

Op za 25 jul. 2020 om 19:55 schreef Geoffrey Poore <notifications@github.com
