### ISSUE TITLE
pysub not respecting commented lines

### ISSUE THREAD

**Issue by ccaprani** [gpoore/pythontex#183]
The `\pysub` command does not respect LaTeX commented lines. MWE below, in which the undefined variables `c` and `d` cause a PythonTeX error. Remove the commented line for it to compile nicely. Now in this simple example, it's clear to see what's happening, but in developing complex files, this bug (?) is insidious. 

I don't think it would be too much for the parser to skip substitutions on lines that are identifiable as LaTeX comments. I've tried debugging PythonTeX, but it hangs on Line 2780 of `pythontex3.py`, so not sure how to go about trying to make a fix for this issue.

```Latex
\documentclass{article}

\usepackage[gobble=auto]{pythontex}

\begin{document}
	
\begin{pycode}[mycode]
	a = 5
	b = 4
\end{pycode}

\begin{pysub}[mycode]
This is $a = !{a}$ and $b = !{b}$.
% but not !{c} or !{d}
\end{pysub}

\end{document}
```

**Comment by gpoore** [comment]
This is actually the intended behavior...the documentation may need to be improved. You can think about `pysub` as a sort of wrapper around something like `"<string>".format(a=a, b=b, c=c, d=d)`. All the substitution happens while completely ignoring any LaTeX meaning of `"<string>"`--it's just treated like a template. Then the result is passed to LaTeX.

In a case like your example, it would probably be possible to find comments and skip them. However, one of the main uses for `pysub` is working with things like TikZ code where symbols don't have their normal LaTeX meanings or macros aren't handled in the normal way, so that commands like `\py` break. It's also possible to have cases where `%` has been redefined not to be a comment.

If you need to be able to comment out lines, I'd recommend using something like this:
```
This is $a = \py{a}$ and $b = \py{b}$.
% but not \py{c} or \py{d}
```

**Comment by ccaprani** [comment]
As ever, thanks @gpoore ! Yes, I eventually found this in developing large complex parametric tikz pictures - not very amenable to an MWE! The `\py` command works perfectly fine of course as you suggest.

I'll make a PR for the documentation on this if you like? Would you prefer it under the `\pys` command, or the `\pysub` environment - I reckon `\pysub` is the right place for it.

A more minor/newb point - is there any guidance on how to set up a debug workflow for PythonTeX? I'd be happy to see if that behaviour is something that can be customized.
