### ISSUE TITLE
Always rerun section if it errored

### ISSUE THREAD

**Issue by Cadair** [gpoore/pythontex#71]
Hi,

When a section of code i.e. `[mygraph]` errors, it is quite often for external reasons, i.e. a library and external script or some data missing, it would be very helpful for me if PythonTeX always reran sections which exited with an error on the last run.

**Comment by gpoore** [comment]
Unless there is a bug, it should already do this by default. For example, if you try to open a file that doesn't exist,
```
\documentclass{article}

\usepackage{pythontex}

\begin{document}

\begin{pycode}[session]
f = open('doesnotexist.txt')
f.close()
\end{pycode}

\end{document}
```
then the code will be executed every time you run `pythontex`, because it never completes successfully. The only reason such code would NOT be executed the next time is if you're using the package or command-line option `rerun`.

**Comment by Cadair** [comment]
yeah, I had rerun=modifed set and and forgotten all about it! Thanks
