### ISSUE TITLE
Issue after updating to mactex 2015

### ISSUE THREAD

**Issue by dholladay00** [gpoore/pythontex#74]
After upgrading to mactex 2015, I receive an error when trying to run the pythontex scripts:
--
This is PythonTeX 0.14
* PythonTeX error
    The version of the PythonTeX scripts does not match the last code
    saved by the document--run LaTeX to create an updated version.
--

Has anyone encountered this issue before?

**Comment by obtitus** [comment]
The error tells you what to do, re-run latex and pythontex and everything should be fine. You could also try a clean if that does not work. 

Mactex probably includes a different version of pythontex then the one you where using. The error is then expected.

**Comment by dholladay00** [comment]
These errors are happening with tex files in which pythontex has not ever executed. Also, I have rerun latex and pythontex, and I continue to get this error in every case.

**Comment by gpoore** [comment]
@dholladay00 The usual cause of these errors is an upgrade, which gets the current version of pythontex out of sync with the version that was last used to compile files. As @obtitus explained, the solution in that case is a complete recompile.

In your case, with new tex files, you are probably dealing with an incomplete uninstall of previous files. There are probably old copies of `pythontex.py`, `pythontex2.py`, `pythontex3.py`, or `pythontex.sty` somewhere on your PATH, and some of these are being found before the new versions. So a combination of old and new code is being used, which triggers an error. If you manually installed pythontex in the past, you might check under the user texmf directory for old files. Otherwise, you might check under you main mactex directory for leftover pieces from a previous version. Just searching for those files by name, and removing the old copies, could also work.

**Comment by tawheeler** [comment]
FWIW I ran into this issue and found that my local `pythontex.sty` file had to have its `\ProvidesPackage{pythontex}` line updated to the new version.
