### ISSUE TITLE
meta-command for pythontex.py and pdflatex.

### ISSUE THREAD

**Issue by TheChymera** [gpoore/pythontex#83]
I find myself constantly running `pdflatex document.tex && pythontex.py document.tex && pdflatex document.tex`. I know I could easily write a script to compact this - but disseminating it to all my machines independently of PythonTeX makes little sense. Would you pull if I wrote a small metascript which does this? If so where should I best place it? https://github.com/gpoore/pythontex/tree/master/pythontex ?

**Comment by gpoore** [comment]
For the moment, I would recommend creating your own script. After you've used it a bit and refined it, I would be willing to consider incorporating it. However, as soon as I do that, then someone else will want it to support `lualatex` and someone else will want `xelatex`, and things will become more complicated--it may start turning into a build tool. And those already exist for LaTeX.

I believe `latexmk` and `rubber` have built-in support for `pythontex` at this point, so using one of those, or a similar build tool, is probably the best option.

**Comment by TheChymera** [comment]
Ok, I did not know about those latex build tools... so running latexmk in the document root automatically runs pythontex.py and rebuilds after that to get the reference linking right? It seems that's what it does. Do you use it?

**Comment by gpoore** [comment]
I usually don't use build tools, because I run `pdflatex` much more than `pythontex`, so I just have a shortcut key for each, and run as needed. For automated documents, I usually just use a Python script with `subprocess`.

Just running `latexmk` may be enough, but you might need a custom `.latexmkrc`. There's a section about it in 4.6.1 in the docs. If it's out of date for the way `latexmk` currently works, let me know, and I'll update it.

**Comment by TheChymera** [comment]
The documentation does not offer any example for the last mentioned use case (when one is using pythontex's dependency tracking system). It just says:

> Ideally, however, PythonTEX would only run once per compile cycle.

Any idea how I can make that happen?

**Comment by gpoore** [comment]
Sorry for the delay in response. The documentation doesn't give an example because I haven't worked with `latexmk` enough to create one.

After quickly looking at the `latexmk` docs, I'm not sure if there's a standard way to do this. Running `pythontex` extra times (for example, after each `pdflatex` run, if you modify `latexmk`'s `-pdflatex` option) will add a little overhead, but in most cases it shouldn't really be noticeable, unless you have lots of dependencies, or are hashing dependencies rather than just checking modification times.

You could use `-pdflatex` to run `pdflatex`, followed by `pythontex`, followed by `pdflatex` every time. That should typically run `pythontex` the minimal number of times. But it would also mean running `pdflatex` an extra time in some cases, which could have more overhead than `pythontex`.
