### ISSUE TITLE
Add support to emulate IPython in the pyconsole

### ISSUE THREAD

**Issue by fernandezc** [gpoore/pythontex#93]
Following the question on http://tex.stackexchange.com/a/224581, I am wondering if you could add support to emulate IPython in the pyconsole environnement ? This would simplify the  writing of tutorial involving IPython. Anyway thanks for your work on this nice and very useful package!

**Comment by gpoore** [comment]
Things haven't really changed since my answer to that question. If an IPython equivalent of Python's `code` module exists, then this should be relatively easy. But I don't know enough about the IPython internals to know whether that exists, and I don't have time to dig deep into IPython to try to find something.

There is an alternative approach to using something like the `code` module. I have a proof-of-concept extension that allows PythonTeX to communicate with interactive processes via pipes. This works with the normal Python and Ruby interpreters, without using any special modules or packages. It is possible that this would work with IPython as well. However, I probably won't be ready to release that extension for at least a few more months. Whenever that happens, I will see if it can communicate with IPython.

**Comment by gpoore** [comment]
This will be continued in #115 .
